// Generated by CoffeeScript 1.9.3

/*
This is a multi line comment.
Also notice that anything in this comment block
gets passed on into the complied JS.
 */

(function() {
  var company, condition, grades, havingFun, i, isOpen, item, j, len, list, list2, menu, num, person, person2, printName, val;

  num = 5;

  company = "Hava Shelia";

  list = [1, 2, 3, 4, 5];

  list2 = ['six', 'seven', 'eight', 'nine', 'ten'];

  person = {
    name: "Dale",
    appropriate: false,
    deskLocation: "Far"
  };

  person2 = {
    name: "Tim",
    awesome: true,
    beersConsumedToday: 0,
    mood: "Thirsty"
  };

  condition = true;

  if (condition === true) {
    condition = false;
  } else {
    condition = true;
  }

  if (!true === !true) {
    console.log("Wait, what?");
  }

  if (true || false && true && !false) {
    console.log("Please stop");
  }

  isOpen = currentTime < closingTime ? true : false;

  havingFun = function() {
    return console.log("Of course we are");
  };

  havingFun();

  printName = function(name) {
    return console.log(name);
  };

  printName("Bob");

  while ((i = 0) < 10) {
    i++;
    val = Math.pow(i, 2);
    if (i === 7) {
      return val;
    }
  }

  menu = ['pasta', 'burrito', 'sushi', 'crab cakes'];

  for (j = 0, len = menu.length; j < len; j++) {
    item = menu[j];
    console.log(item);
  }

  grades = [];

}).call(this);
